### ISSUE TITLE
Remove notebook content from README

### ISSUE THREAD

**Issue by rhagarty** [IBM/visualize-food-insecurity#1]
Lots of good info in README, but most of the steps describe is repeated in the notebook. I think you should just describe what you are going to accomplish/show with the notebook, then provide the steps to run it. Once there, they can see all of the specific detail about each of the steps/cells.

**Comment by MadisonJMyers** [comment]
Let me know if my update works! Not sure if I took away too much or too little! Also I'm not quite sure what a badge is so if you could direct me to the place where I could educate myself on what to put, that would be super helpful. Thanks in advance! @rhagarty

**Comment by MadisonJMyers** [comment]
@rhagarty I also can't find the "With Watson" text to copy and paste. Do you mind directing me there as well?

**Comment by rhagarty** [comment]
Badges are at the top of the repo, and I can show you how to add some once we move to IBM.

And don't worry about "With Wason". In fact, remove what you have. We have a new section for that that I can add later.

**Comment by rhagarty** [comment]
And update of README is looking good!

**Comment by MadisonJMyers** [comment]
Awesome! I moved everything into their appropriate folders (I'm still unsure if Maintainers.md and contributing.md need to be somewhere else or not?). Let me know if I need to do anything else or open a PR.
