### ISSUE TITLE
Need journey files

### ISSUE THREAD

**Issue by rhagarty** [IBM/visualize-food-insecurity#2]
From other Spark journeys, copy the following files:
ACKNOWLEDGMENT.md  (add appropriate contributors here)
CONTRIBUTING.md  (update links in the file to point to your repo - this can wait until you move to IBM)
MAINTAINERS.md  (no changes needed)

**Comment by MadisonJMyers** [comment]
Complete though I did not add an acknowledgement as I do not have contributors.

**Comment by rhagarty** [comment]
That where we put our names, as well as anyone else who might help out. Names should be linked to github accounts.
