### ISSUE TITLE
Issue on exporting dataframe/file

### ISSUE THREAD

**Issue by markoviksten** [IBM/visualize-food-insecurity#29]
I´m in problem in the end of notebook to download dataframe from DSX to csv file (in order to import it to WA)

So according to this help I should get something like this ( https://medium.com/ibm-data-science-experience/working-with-object-storage-in-data-science-experience-python-edition-c96bc6c6101)

```
credentials_1 = {
        'auth_url': 'https://identity.open.softlayer.com',
        'project': 'object_storage_9-----3',
        'project_id': '7babac2********e0',
        'region': 'dallas',
        'user_id': '9603b8************70f',
        'domain_id': '2c66d***********b9d26',
        'domain_name': '1026***',
        'username': 'member_******************',
        'password': ""
        "***************"
        "",
        'container': 'TemplateNotebooks',
        'tenantId': 'undefined',
        'filename': 'data_by_var.json'
}
```

But instead I´m getting code like this :

```
credentials_100 = {
'IBM_API_KEY_ID': 'api-key-here',
'IAM_SERVICE_ID': 'service-id-here',
'ENDPOINT': 'https://s3-api.us-geo.objectstorage.service.networklayer.com',
'IBM_AUTH_ENDPOINT': 'https://iam.ng.bluemix.net/oidc/token',
'BUCKET': 'bucket-name-really-in-here',
'FILE': 'combined_data.csv'
}
```

It doesnt inclyude user_id etc. which are required in next notebook cell def_putfile - call and as you have in your examåple

What I´m doing wrong in here and anyidea how to fix this? Thanks a lot for great example =)

**Comment by stevemar** [comment]
Thanks @markoviksten -- @scottdangelo will look into this as he is fixes similar bugs in other repos.

**Comment by scottdangelo** [comment]
I'm working on testing and documenting a fix for this. IN the meantime, you can:
1. insert your credentials in a cell as you have done above
2. paste the following in a new cell and run it:
```
import ibm_boto3
from ibm_botocore.client import Config

cos = ibm_boto3.client(service_name='s3',
    ibm_api_key_id=credentials['IBM_API_KEY_ID'],
    ibm_service_instance_id=credentials['IAM_SERVICE_ID'],
    ibm_auth_endpoint=credentials['IBM_AUTH_ENDPOINT'],
    config=Config(signature_version='oauth'),
    endpoint_url=credentials['ENDPOINT'])

cos.upload_file(Filename='df_focusedvalues.csv',Bucket=credentials['BUCKET'],Key='df_focusedvalues.csv')
```
3. Don't run (and/or delete) the rest of the cells. i.e. the ones with `def put_file....` and `put_file(credentials_98,'df_focusedvalues.csv')`

I haven't tested this in Watson Analytics, as I am having trouble with sign on issues. But this *should* fix things for you.
