### ISSUE TITLE
Need architecture diagram to README along with flow discription

### ISSUE THREAD

**Issue by rhagarty** [IBM/visualize-food-insecurity#3]
See other Spark journeys for examples.

Note, diagram should be placed in /doc/source/images/architecture.png

**Comment by MadisonJMyers** [comment]
Complete- still working on some aspects of the README but this is complete. Renamed FoodInsecurityArchitecture.png to Architecture.png in my images file.

**Comment by rhagarty** [comment]
still need to move the png file to /doc/source/images
