### ISSUE TITLE
Add included components and featured technologies to README

### ISSUE THREAD

**Issue by rhagarty** [IBM/visualize-food-insecurity#4]
See other Spark journeys for examples, as well as https://github.ibm.com/developer-journeys/journey-docs for appropriate descriptions.

**Comment by MadisonJMyers** [comment]
Still working on some aspects of the README but this is complete.

**Comment by rhagarty** [comment]
still need to add links to the lists. e.g. 'Data Science' should be a link to the DSX page.

**Comment by MadisonJMyers** [comment]
Just to clarify, I should have links in the links section as well as after each listed technology/component?

**Comment by MadisonJMyers** [comment]
@rhagarty I think I figured out what you meant. Let me know if that looks good to you now. Thanks! Also, if you want me to open a PR now please let me know.

**Comment by rhagarty** [comment]
Looks good.
