### ISSUE TITLE
Notebook getting warnings

### ISSUE THREAD

**Issue by rhagarty** [IBM/visualize-food-insecurity#44]
@MadisonJMyers - using the latest version of IBM Watson Studio, I'm getting warnings in a couple of cells which I don't recall seeing before. The notebook appears to run correctly, but you should probably check it out.

Cell 2 - /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (208,209,211,214) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Cell 13 - /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/seaborn/categorical.py:1460: FutureWarning: remove_na is deprecated and is a private function. Do not use.
  stat_data = remove_na(group_data)

**Comment by it40093** [comment]
I have same issue, how did you solve it?

**Comment by rhagarty** [comment]
@it40093 - issue was not resolved as the original developer is no longer maintaining this notebook. I found the notebook still completed, despite the warnings. Is this not the case for you?
