### ISSUE TITLE
Issues creating Data Science projects in current steps

### ISSUE THREAD

**Issue by timroster** [IBM/visualize-food-insecurity#51]
When signing up for Watson Studio using the link in:

https://github.com/IBM/visualize-food-insecurity?cm_sp=Developer-_-create-visualizations-to-understand-food-insecurity-_-Get-the-Code#1-sign-up-for-the-watson-studio

The Watson Studio account doesn't provide tooling for creating a Data Science project. Instead using the IBM Cloud Catalog to create the service instance for Watson Studio needs be used to be able to see the option for Data Science projects.

**Comment by stevemar** [comment]
closing this as the instructions have been updated since, but we'll be sunsetting this pattern as Watson Analytics no longer provides a free tier friendly option.
