### ISSUE TITLE
README changes

### ISSUE THREAD

**Issue by rhagarty** [IBM/visualize-food-insecurity#6]
@MadisonJMyers - nice progress, but still needs some minor tweeks. This will be easier once we move this repo to IBM, where I can just make changes directly.

1) remove the dashes from your title
2) remove the everything after that until the "This journey will guide ...". This will be your intro paragraph.
3) remove the "architecture image" tag and title for your diagram.
4) substitute the word "journey" with "Code Pattern".
4) "Steps". Each of the steps should be a title with a section. Please check out how Dilip's does this in his journey in the section "Run using a jupyter notebook in the IBM data science experience". 

Assuming your journey only runs in a notebook, your steps should probably mimic his journey steps. Note that each step has a section to provide details on how to accomplish the step. If you have additional steps on loading data, you would add those steps here. 

We can talk about this more on Slack...

**Comment by MadisonJMyers** [comment]
Great! I did 1-4 (though let me know if I missed something). For 5, could you direct me to Dilip's journey? Thanks!

**Comment by rhagarty** [comment]
Looks good. We can do the rest once we move the repo to IBM
